"""Inactive one-use synthetic payload framing; no authority or resource access.

The trusted transport owns the key, session and harmless generated bytes. A
receipt is only the peer's exact discard claim, never delivery permission or a
claim that bytes did not cross the private pipe. This codec has no clock or I/O.
"""
import base64
from dataclasses import dataclass, field
import hashlib
import hmac
import re
from threading import RLock

from .broker_protocol import BrokerProtocolError, MAX_BODY_BYTES, MAX_DATA_BYTES, _canonical
from .broker_recipient_protocol import RecipientWitnessExchange
from .json_input import loads

_MODE = 'synthetic_transport_discard_only'
_MEANING = 'Inactive synthetic transport discard claim; not authority or protected delivery proof.'
_RLOCK_TYPE = type(RLock())


def _synthetic_binding(value):
    if type(value) is not dict or set(value) != {
            'revision', 'mode', 'transport_id', 'fixture_id', 'byte_count', 'digest', 'channel'}:
        raise ValueError('invalid_synthetic_binding')
    if (type(value['revision']) is not int or value['revision'] != 1
            or type(value['mode']) is not str or value['mode'] != _MODE
            or type(value['byte_count']) is not int or not 0 <= value['byte_count'] <= MAX_DATA_BYTES):
        raise ValueError('unsupported_synthetic_binding')
    for name in ('transport_id', 'fixture_id', 'digest'):
        if type(value[name]) is not str or re.fullmatch('[0-9a-f]{64}', value[name]) is None:
            raise ValueError('invalid_synthetic_identifier')
    channel = value['channel']
    if type(channel) is not dict or set(channel) != {'pid', 'creation_time', 'witness_session'}:
        raise ValueError('invalid_synthetic_channel')
    if (type(channel['pid']) is not int or not 1 <= channel['pid'] <= 0xffffffff
            or type(channel['creation_time']) is not int or not 1 <= channel['creation_time'] <= 0xffffffffffffffff
            or type(channel['witness_session']) is not str
            or re.fullmatch('[0-9a-f]{64}', channel['witness_session']) is None):
        raise ValueError('invalid_synthetic_channel')
    if len({value['transport_id'], value['fixture_id'], channel['witness_session']}) != 3:
        raise ValueError('synthetic_identity_collision')
    if not value['byte_count'] and value['digest'] != hashlib.sha256(b'').hexdigest():
        raise ValueError('invalid_empty_synthetic_digest')
    snapshot = _canonical(value)
    if len(snapshot) > MAX_BODY_BYTES:
        raise ValueError('synthetic_binding_too_large')
    return snapshot


@dataclass(frozen=True)
class SyntheticPayloadEvidence:
    canonical_binding: bytes = field(repr=False)
    binding_digest: str
    outcome: str
    byte_count: int
    digest: str
    meaning: str = field(default=_MEANING, init=False)

    def inspect(self): return loads(self.canonical_binding)
    def __bool__(self): raise TypeError('Synthetic payload evidence is not permission or delivery proof')


class SyntheticPayloadExchange(RecipientWitnessExchange):
    """Prepare -> ready -> one bounded payload -> discard receipt, then spent.

    The receiving endpoint never returns data. Its original private bytearray
    must be verified and wiped before a receipt may be constructed. Exact
    transcripts, role, session and binding prevent retry or endpoint splicing.
    Arbitrary code inside this trusted Python process remains outside the claim.
    """
    _binding_bytes = staticmethod(_synthetic_binding)

    def __init__(self, *, role, key, session):
        super().__init__(role=role, key=key, session=session)
        if hmac.compare_digest(key, session):
            # The session appears in public binding metadata; it must never be
            # the secret used to authenticate those same frames.
            RecipientWitnessExchange._failed(self)
            raise BrokerProtocolError('invalid_bootstrap')
        self._issued_lock = self._lock
        self._buffer = self._issued_buffer = self._recovery_buffer = None
        self._buffer_snapshot = None
        self._discarded = self._discard_snapshot = False

    def _mac(self, direction, body):
        domain = b'SecurityBrightness.inactive-synthetic-payload.v1\0'
        key = hmac.digest(self._key, domain+direction.encode('ascii'), hashlib.sha256)
        return hmac.digest(key, domain+body, hashlib.sha256)

    def _capture(self, value):
        super()._capture(value)
        if loads(self._binding_snapshot)['channel']['witness_session'] != self._session:
            raise ValueError('synthetic_session_mismatch')

    def _integrity(self, *, captured=False, payload_captured=False):
        if (type(self._lock) is not _RLOCK_TYPE or self._lock is not self._issued_lock):
            raise ValueError('changed_synthetic_lock')
        super()._integrity(captured=captured)
        if self._binding_snapshot is not None:
            if loads(self._binding_snapshot)['channel']['witness_session'] != self._session:
                raise ValueError('changed_synthetic_session')
        if (type(self._discarded) is not bool or type(self._discard_snapshot) is not bool
                or self._discarded is not self._discard_snapshot):
            raise ValueError('changed_synthetic_discard_state')
        buffered = self._role == 'broker' and (self._step == 3 or payload_captured)
        if not buffered:
            if (self._buffer is not None or self._issued_buffer is not None or self._recovery_buffer is not None
                    or self._buffer_snapshot is not None or self._discarded):
                raise ValueError('unexpected_synthetic_buffer')
            return
        binding = loads(self._binding_snapshot)
        if (type(self._buffer) is not bytearray or self._buffer is not self._issued_buffer
                or self._buffer is not self._recovery_buffer or type(self._buffer_snapshot) is not tuple
                or len(self._buffer_snapshot) != 2 or type(self._buffer_snapshot[0]) is not int
                or type(self._buffer_snapshot[1]) is not str
                or self._buffer_snapshot != (binding['byte_count'], binding['digest'])):
            raise ValueError('changed_synthetic_buffer')
        if self._discarded:
            if len(self._buffer): raise ValueError('incomplete_synthetic_discard')
        elif (len(self._buffer) != binding['byte_count']
                or hashlib.sha256(self._buffer).hexdigest() != binding['digest']):
            raise ValueError('changed_synthetic_bytes')

    def _evidence(self, outcome):
        value = loads(self._binding_snapshot)
        return SyntheticPayloadEvidence(self._binding_snapshot, self._binding_digest, outcome,
                                        value['byte_count'], value['digest'])

    def _checked_evidence(self, outcome):
        result = self._evidence(outcome)
        value = loads(self._binding_snapshot)
        if (type(result) is not SyntheticPayloadEvidence
                or type(result.canonical_binding) is not bytes or result.canonical_binding != self._binding_snapshot
                or type(result.binding_digest) is not str or result.binding_digest != self._binding_digest
                or type(result.outcome) is not str or result.outcome != outcome
                or type(result.byte_count) is not int or result.byte_count != value['byte_count']
                or type(result.digest) is not str or result.digest != value['digest']
                or type(result.meaning) is not str or result.meaning != _MEANING):
            raise ValueError('changed_synthetic_evidence')
        return result

    def _expected(self, phase):
        if phase not in (1, 3): raise ValueError('invalid_synthetic_phase')
        value = loads(self._binding_snapshot)
        return dict(revision=1, mode=_MODE, binding_digest=self._binding_digest,
                    outcome='prepared' if phase == 1 else 'peer_discarded',
                    byte_count=value['byte_count'], digest=value['digest'])

    @staticmethod
    def _wipe(buffer):
        # Zero before clearing: an unexpected exported view must not retain the
        # old content even when it prevents resizing the original bytearray.
        bytearray.__setitem__(buffer, slice(None), b'\0'*len(buffer))
        try: bytearray.clear(buffer)
        except BufferError: pass

    def _failed(self):
        # Three original aliases permit cleanup after one pointer is replaced.
        # Never invoke methods on a substituted arbitrary object or wipe a lone
        # foreign bytearray. This is corruption handling, not hostile-code proof.
        candidates = [self.__dict__.get(name) for name in ('_buffer', '_issued_buffer', '_recovery_buffer')]
        # Retirement is unconditional even if cleanup hits a memory or buffer
        # failure. Retain the original aliases only for a later cleanup attempt;
        # they cannot restore a spent key or make another frame available.
        super()._failed()
        self._discarded = self._discard_snapshot = False
        for buffer in candidates:
            if type(buffer) is bytearray and sum(item is buffer for item in candidates) >= 2:
                try: self._wipe(buffer)
                except BaseException:
                    self._buffer = self._issued_buffer = self._recovery_buffer = buffer
                    raise BrokerProtocolError('synthetic_payload_rejected') from None
                break
        self._buffer = self._issued_buffer = self._recovery_buffer = None
        self._buffer_snapshot = None

    def _exchange(self, role, step, operation):
        with self._original_lock():
            try:
                self._check(role, step)
                result, frame = operation()
                self._integrity(captured=step == 0, payload_captured=step == 2 and role == 'broker')
                self._advance(frame)
                if self._step == 4: self._failed()
                else: self._integrity()
                return result
            except Exception:
                self._failed()
                raise BrokerProtocolError('synthetic_payload_rejected') from None

    def prepare(self, binding): return RecipientWitnessExchange.request(self, binding)

    def accept_prepare(self, frame):
        def operation():
            self._capture(self._message('request', frame))
            return self._checked_evidence('requested'), frame
        return self._exchange('broker', 0, operation)

    def ready(self): return self._send(1, 'broker', 'reply')
    def accept_ready(self, frame): return self._receive(1, 'coordinator', 'reply', frame, 'prepared')

    def payload(self, data):
        def operation():
            value = loads(self._binding_snapshot)
            if (type(data) is not bytes or len(data) != value['byte_count']
                    or hashlib.sha256(data).hexdigest() != value['digest']):
                raise ValueError('invalid_synthetic_payload')
            message = dict(revision=1, mode=_MODE, binding_digest=self._binding_digest,
                           byte_count=value['byte_count'], digest=value['digest'],
                           data=base64.b64encode(data).decode('ascii'))
            frame = self._frame('request', message)
            if _canonical(self._message('request', frame)) != _canonical(message):
                raise ValueError('changed_synthetic_payload_frame')
            return frame, frame
        return self._exchange('coordinator', 2, operation)

    def accept_payload(self, frame):
        def operation():
            value = loads(self._binding_snapshot)
            message = self._message('request', frame)
            if (type(message) is not dict or set(message) != {
                    'revision', 'mode', 'binding_digest', 'byte_count', 'digest', 'data'}
                    or type(message['revision']) is not int or message['revision'] != 1
                    or type(message['mode']) is not str or message['mode'] != _MODE
                    or type(message['binding_digest']) is not str or message['binding_digest'] != self._binding_digest
                    or type(message['byte_count']) is not int or message['byte_count'] != value['byte_count']
                    or type(message['digest']) is not str or message['digest'] != value['digest']
                    or type(message['data']) is not str or len(message['data']) > 5464):
                raise ValueError('invalid_synthetic_payload_message')
            data = base64.b64decode(message['data'], validate=True)
            if (base64.b64encode(data).decode('ascii') != message['data']
                    or len(data) != value['byte_count']
                    or hashlib.sha256(data).hexdigest() != value['digest']):
                raise ValueError('invalid_synthetic_payload_bytes')
            self._buffer = self._issued_buffer = self._recovery_buffer = bytearray(data)
            self._buffer_snapshot = (value['byte_count'], value['digest'])
            return self._checked_evidence('buffered_private'), frame
        return self._exchange('broker', 2, operation)

    def discard(self):
        with self._original_lock():
            try:
                self._check('broker', 3)
                if self._discarded: raise ValueError('duplicate_synthetic_discard')
                self._wipe(self._buffer)
                self._discarded = self._discard_snapshot = True
                self._integrity()
            except Exception:
                self._failed()
                raise BrokerProtocolError('synthetic_payload_rejected') from None

    def _original_lock(self):
        lock = self.__dict__.get('_issued_lock')
        if type(lock) is not _RLOCK_TYPE or self.__dict__.get('_lock') is not lock:
            self._failed()
            raise BrokerProtocolError('synthetic_payload_rejected')
        return lock

    def close(self):
        with self._original_lock(): self._failed()

    def receipt(self):
        def operation():
            if not self._discarded: raise ValueError('synthetic_payload_not_discarded')
            frame = self._frame('reply', self._expected(3))
            if _canonical(self._message('reply', frame)) != _canonical(self._expected(3)):
                raise ValueError('changed_synthetic_receipt_frame')
            return frame, frame
        return self._exchange('broker', 3, operation)

    def accept_receipt(self, frame):
        return self._receive(3, 'coordinator', 'reply', frame, 'peer_discarded')

    def _unsupported(self, *args, **kwargs):
        self.close(); raise BrokerProtocolError('synthetic_payload_rejected')

    request = accept_request = prove = accept_proof = retire = accept_retirement = _unsupported
    acknowledge_retirement = accept_ack = reply = accept_reply = _unsupported
    dry_commit = accept_dry_commit = model_visibility = accept_model_visibility = _unsupported
    receipt_claim = accept_receipt_claim = data = read = publish = deliver = _unsupported
    retire_for_check = accept_retirement_ack = _unsupported
