"""Generated bytes on one fixed inactive native peer; no protected resources."""
from contextlib import contextmanager
from dataclasses import FrozenInstanceError, asdict
import copy
import hashlib
import inspect
import math
import os
from pathlib import Path
import tempfile
import threading
import time
import unittest
from unittest.mock import patch

from core import broker_synthetic_payload_transport as native
from core import broker_synthetic_payload_peer as process
from core.broker_process import BrokerProcessError
from core.broker_synthetic_payload_protocol import SyntheticPayloadExchange


class SyntheticPayloadTransportTests(unittest.TestCase):
    DATA = b'SecurityBrightness generated transport test\x00\xff\n'

    def setUp(self):
        self.gate = None

    def new(self, payload=None, **options):
        if payload is None: payload = self.DATA
        self.gate = native.SyntheticPayloadTransport(payload, **options)
        return self.gate

    def diagnostic(self):
        value = self.gate.inspect()
        self.assertEqual(set(value), {'state', 'payload_may_have_been_visible',
            'payload_frame_bytes_written', 'cleanup_confirmed'})
        self.assertIs(type(value['state']), str)
        for name in ('payload_may_have_been_visible', 'cleanup_confirmed'):
            self.assertIs(type(value[name]), bool)
        self.assertIs(type(value['payload_frame_bytes_written']), int)
        self.assertGreaterEqual(value['payload_frame_bytes_written'], 0)
        self.assertLessEqual(value['payload_frame_bytes_written'], 8192 + 36)
        self.assertNotIn('data', value)
        self.assertNotIn('payload', value)
        self.assertNotIn('released_bytes', value)
        return value

    def rejected(self, operation=None, *, visible=None, cleanup=True):
        with self.assertRaises(native.SyntheticPayloadTransportError) as error:
            (operation or self.gate.run)()
        self.assertNotIn(repr(self.DATA), str(error.exception))
        value = self.diagnostic()
        self.assertNotEqual(value['state'], 'peer_discarded')
        if visible is not None:
            self.assertIs(value['payload_may_have_been_visible'], visible)
            self.assertEqual(value['state'], 'outcome_unknown' if visible else value['state'])
        self.assertIs(value['cleanup_confirmed'], cleanup)
        return value

    def helper(self, *, prefix='', ending=''):
        directory = tempfile.TemporaryDirectory(); self.addCleanup(directory.cleanup)
        path = Path(directory.name) / 'generated-payload-fault.py'
        root = str(Path(__file__).resolve().parent.parent)
        path.write_text('import sys,os,time\nsys.path.insert(0,' + repr(root) + ')\n'
            'from core import broker_synthetic_payload_entry as entry\n' + prefix +
            '\nentry.run()\n' + ending, encoding='utf-8')
        return patch.object(process._SyntheticPayloadPeer, '_entry_path', return_value=path)

    @contextmanager
    def payload_write(self, operation):
        """Fault only the actual payload frame, after genuine native readiness."""
        original_payload, original_write = SyntheticPayloadExchange.payload, os.write
        active, reached = [False], []
        def payload(codec, data):
            value = original_payload(codec, data)
            active[0] = True
            return value
        def write(fd, data):
            if active[0]:
                reached.append(len(data))
                return operation(original_write, fd, data)
            return original_write(fd, data)
        with patch.object(SyntheticPayloadExchange, 'payload', payload), patch.object(native.os, 'write', write):
            yield reached

    def ready_fault(self, operation):
        original, reached = SyntheticPayloadExchange.accept_ready, []
        def ready(codec, frame):
            value = original(codec, frame)
            self.assertIsNone(self.gate._issued_child.poll())
            reached.append(True)
            operation()
            return value
        with patch.object(SyntheticPayloadExchange, 'accept_ready', ready):
            value = self.rejected(visible=False)
        self.assertEqual(reached, [True], 'fault follows authenticated original native readiness')
        return value

    def receipt_fault(self, operation, *, cleanup=True):
        original, reached = SyntheticPayloadExchange.accept_receipt, []
        def receipt(codec, frame):
            child = self.gate._issued_child
            self.assertEqual(child.poll(), 0)
            value = original(codec, frame)
            reached.append(True)
            operation(value)
            return value
        with patch.object(SyntheticPayloadExchange, 'accept_receipt', receipt):
            value = self.rejected(visible=True, cleanup=cleanup)
        self.assertEqual(reached, [True], 'fault follows exact receipt and original zero process exit')
        return value

    def success(self, payload=None, **options):
        gate = self.new(payload, **options)
        data = self.DATA if payload is None else payload
        value = gate.run()
        self.assertEqual((value.outcome, value.byte_count, value.digest),
            ('peer_discarded', len(data), hashlib.sha256(data).hexdigest()))
        self.assertIs(type(value.canonical_binding), bytes)
        self.assertLessEqual(len(value.canonical_binding), 8192)
        self.assertEqual(value.binding_digest, hashlib.sha256(value.canonical_binding).hexdigest())
        self.assertNotIn('data', asdict(value)); self.assertNotIn('released_bytes', asdict(value))
        with self.assertRaises(TypeError): bool(value)
        with self.assertRaises(FrozenInstanceError): value.outcome = 'allow'
        current = self.diagnostic()
        self.assertEqual(current['state'], 'peer_discarded')
        self.assertIs(current['payload_may_have_been_visible'], True)
        self.assertIs(current['cleanup_confirmed'], True)
        self.assertGreater(current['payload_frame_bytes_written'], len(data))
        gate._issued_child._retired()
        self.assertEqual(gate._issued_child._exit, 0)
        return value

    def test_real_fixed_peer_discards_binary_generated_bytes_and_joins(self):
        self.success()

    def test_real_empty_payload_still_crosses_one_use_frame_boundary(self):
        self.success(b'')

    def test_real_one_byte_payload(self):
        self.success(b'\x00')

    def test_real_maximum_payload_remains_bounded(self):
        self.success(bytes(range(256)) * 16)

    def test_constructor_accepts_no_endpoint_file_handle_app_authority_or_executor(self):
        signature = inspect.signature(native.SyntheticPayloadTransport)
        self.assertEqual(list(signature.parameters), ['payload', 'timeout'])
        for field in ('path', 'endpoint', 'handle', 'application', 'credential', 'approval', 'executor'):
            with self.subTest(field=field), self.assertRaises(TypeError):
                native.SyntheticPayloadTransport(self.DATA, **{field: 'caller'})
        self.assertEqual(list(inspect.signature(process._SyntheticPayloadPeer).parameters), [])
        gate = self.new()
        for field in ('authorize', 'publish', 'read_file', 'execute', 'release', 'acquire'):
            self.assertFalse(hasattr(gate, field))
        self.assertEqual(process._SyntheticPayloadPeer._entry_path(None).name,
            'broker_synthetic_payload_entry.py')

    def test_constructor_rejects_mutable_text_foreign_types_and_bytes_subclasses(self):
        class ForeignBytes(bytes): pass
        for value in (None, True, 1, '', self.DATA.decode('latin1'), bytearray(self.DATA),
                      memoryview(self.DATA), ForeignBytes(self.DATA), {'data': self.DATA}):
            with self.subTest(type=type(value)), self.assertRaises((TypeError, ValueError, native.SyntheticPayloadTransportError)):
                native.SyntheticPayloadTransport(value)

    def test_constructor_rejects_oversized_payload_before_native_launch(self):
        with patch.object(native, '_SyntheticPayloadPeer') as launch:
            with self.assertRaises((TypeError, ValueError, native.SyntheticPayloadTransportError)):
                native.SyntheticPayloadTransport(b'x' * 4097)
            launch.assert_not_called()

    def test_constructor_rejects_malformed_or_unbounded_deadlines(self):
        for value in (None, True, False, 0, -1, 5.0001, math.inf, -math.inf, math.nan, '1'):
            with self.subTest(value=value), self.assertRaises((TypeError, ValueError, native.SyntheticPayloadTransportError)):
                native.SyntheticPayloadTransport(self.DATA, timeout=value)

    def test_inspect_is_detached_and_cannot_manufacture_state_or_visibility(self):
        self.new(); first = self.diagnostic()
        self.assertEqual(first, dict(state='not_started', payload_may_have_been_visible=False,
            payload_frame_bytes_written=0, cleanup_confirmed=False))
        first.update(state='peer_discarded', payload_may_have_been_visible=True, cleanup_confirmed=True)
        self.assertEqual(self.diagnostic()['state'], 'not_started')

    def test_cancel_before_run_emits_no_payload_and_cannot_be_retried(self):
        self.new(); self.gate.cancel()
        first = self.rejected(visible=False)
        self.assertEqual(first['state'], 'cancelled_before_payload')
        self.assertEqual(first['payload_frame_bytes_written'], 0)
        self.rejected(visible=False)

    def test_repeat_success_cannot_relaunch_or_send_another_payload(self):
        self.success()
        child = self.gate._issued_child
        with patch.object(native, '_SyntheticPayloadPeer') as launch:
            with self.assertRaises(native.SyntheticPayloadTransportError): self.gate.run()
            launch.assert_not_called()
        self.assertIs(self.gate._issued_child, child)

    def test_cancel_after_success_cannot_clear_spent_attempt(self):
        self.success(); self.gate.cancel()
        with self.assertRaises(native.SyntheticPayloadTransportError): self.gate.run()

    def test_elapsed_prelaunch_deadline_prevents_native_launch(self):
        self.new(timeout=.03); time.sleep(.04)
        with patch.object(native, '_SyntheticPayloadPeer') as launch:
            value = self.rejected(visible=False)
            launch.assert_not_called()
        self.assertEqual(value['state'], 'failed_before_payload')

    def test_cancellation_after_authenticated_ready_never_attempts_payload_write(self):
        self.new(); value = self.ready_fault(self.gate.cancel)
        self.assertEqual(value['state'], 'cancelled_before_payload')
        self.assertEqual(value['payload_frame_bytes_written'], 0)

    def test_buffer_mutation_after_ready_prevents_payload_write(self):
        self.new(); self.ready_fault(lambda: self.gate._origin.buffer.__setitem__(0, 0))

    def test_original_buffer_is_wiped_after_success(self):
        self.new(); buffer = self.gate._origin.buffer
        self.gate.run(); self.assertEqual(buffer, bytearray())

    def test_original_buffer_is_wiped_after_previsibility_failure(self):
        self.new(); buffer = self.gate._origin.buffer
        self.ready_fault(self.gate.cancel)
        self.assertEqual(buffer, bytearray())

    def test_multiple_native_partial_writes_complete_exact_bounded_frame(self):
        self.new()
        def short(original, fd, data): return original(fd, data[:7])
        with self.payload_write(short) as reached:
            result = self.gate.run()
        self.assertGreater(len(reached), 2)
        self.assertEqual(result.digest, hashlib.sha256(self.DATA).hexdigest())
        self.assertEqual(self.diagnostic()['state'], 'peer_discarded')

    def test_partial_payload_write_then_cancel_is_unknown_and_spent(self):
        self.new()
        def short(original, fd, data):
            count = original(fd, data[:7]); self.gate.cancel(); return count
        with self.payload_write(short) as reached:
            value = self.rejected(visible=True)
        self.assertEqual(len(reached), 1)
        self.assertEqual(value['payload_frame_bytes_written'], 7)
        self.assertEqual(self.gate._origin.buffer, bytearray())
        self.rejected(visible=True)

    def test_blocking_payload_attempt_then_cancel_is_unknown_even_with_no_accepted_bytes(self):
        self.new()
        def blocked(original, fd, data):
            self.gate.cancel(); raise BlockingIOError()
        with self.payload_write(blocked) as reached:
            value = self.rejected(visible=True)
        self.assertEqual(len(reached), 1)
        self.assertEqual(value['payload_frame_bytes_written'], 0)

    def test_zero_payload_write_is_unknown_not_false_zero_release_claim(self):
        self.new()
        with self.payload_write(lambda original, fd, data: 0):
            self.rejected(visible=True)

    def test_broken_pipe_at_payload_boundary_is_unknown(self):
        self.new()
        def broken(original, fd, data): raise BrokenPipeError('generated payload fault')
        with self.payload_write(broken): self.rejected(visible=True)

    def test_invalid_boolean_payload_write_count_fails_closed(self):
        self.new()
        with self.payload_write(lambda original, fd, data: True): self.rejected(visible=True)

    def test_invalid_negative_payload_write_count_fails_closed(self):
        self.new()
        with self.payload_write(lambda original, fd, data: -1): self.rejected(visible=True)

    def test_invalid_oversized_payload_write_count_fails_closed(self):
        self.new()
        with self.payload_write(lambda original, fd, data: len(data)+1): self.rejected(visible=True)

    def test_bounded_timeout_after_repeated_blocking_payload_writes_is_unknown(self):
        self.new(timeout=1.5)
        def blocked(original, fd, data): raise BlockingIOError()
        with self.payload_write(blocked) as reached:
            started = time.monotonic(); self.rejected(visible=True)
        self.assertGreater(len(reached), 1)
        self.assertLess(time.monotonic()-started, 3)

    def test_missing_receipt_after_child_discard_cannot_establish_success(self):
        self.new()
        prefix = 'entry.SyntheticPayloadExchange.receipt = lambda self: os._exit(0)'
        with self.helper(prefix=prefix): self.rejected(visible=True)

    def test_truncated_receipt_after_discard_is_unknown(self):
        self.new()
        prefix = 'original = entry.SyntheticPayloadExchange.receipt\nentry.SyntheticPayloadExchange.receipt = lambda self: original(self)[:-1]'
        with self.helper(prefix=prefix): self.rejected(visible=True)

    def test_corrupt_receipt_mac_after_discard_is_unknown(self):
        self.new()
        prefix = ('original = entry.SyntheticPayloadExchange.receipt\n'
            'def receipt(self):\n frame = original(self)\n return frame[:-1]+bytes([frame[-1]^1])\n'
            'entry.SyntheticPayloadExchange.receipt = receipt')
        with self.helper(prefix=prefix): self.rejected(visible=True)

    def test_replayed_receipt_in_same_output_is_trailing_and_unknown(self):
        self.new()
        prefix = 'original = entry.SyntheticPayloadExchange.receipt\nentry.SyntheticPayloadExchange.receipt = lambda self: original(self)*2'
        with self.helper(prefix=prefix): self.rejected(visible=True)

    def test_trailing_output_after_valid_receipt_is_unknown(self):
        self.new()
        with self.helper(ending="os.write(1,b'extra')"): self.rejected(visible=True)

    def test_nonzero_exit_after_valid_receipt_is_unknown(self):
        self.new()
        with self.helper(ending='sys.exit(7)'): self.rejected(visible=True)

    def test_crash_after_payload_acceptance_is_unknown(self):
        self.new()
        prefix = ('original = entry.SyntheticPayloadExchange.accept_payload\n'
            'def payload(self, frame):\n original(self,frame)\n os._exit(9)\n'
            'entry.SyntheticPayloadExchange.accept_payload = payload')
        with self.helper(prefix=prefix): self.rejected(visible=True)

    def test_peer_hang_after_valid_receipt_times_out_and_original_child_is_joined(self):
        self.new(timeout=1.5)
        with self.helper(ending='time.sleep(10)'): self.rejected(visible=True)
        self.gate._issued_child._retired()

    def test_cancel_while_waiting_for_receipt_is_unknown(self):
        self.new()
        original = process._SyntheticPayloadPeer.close_input
        def close_input(child):
            value = original(child); self.gate.cancel(); return value
        with patch.object(process._SyntheticPayloadPeer, 'close_input', close_input):
            self.rejected(visible=True)

    def test_wrong_startup_pid_fails_before_payload(self):
        self.new()
        prefix = 'original = entry.ready\nentry.ready = lambda key,session,pid: original(key,session,pid+1)'
        with self.helper(prefix=prefix): self.rejected(visible=False)

    def test_wrong_startup_session_fails_before_payload(self):
        self.new()
        prefix = 'original = entry.ready\nentry.ready = lambda key,session,pid: original(key,b"x"*32,pid)'
        with self.helper(prefix=prefix): self.rejected(visible=False)

    def test_corrupt_startup_mac_fails_before_payload(self):
        self.new()
        prefix = ('original = entry.ready\ndef ready(*args):\n value = original(*args)\n'
            ' return value[:-1]+bytes([value[-1]^1])\nentry.ready=ready')
        with self.helper(prefix=prefix): self.rejected(visible=False)

    def test_extra_startup_output_cannot_be_ready_frame(self):
        self.new()
        prefix = 'original = entry.ready\nentry.ready = lambda *args: original(*args)+b"malformed"'
        with self.helper(prefix=prefix): self.rejected(visible=False)

    def test_child_crash_before_startup_is_failed_before_payload(self):
        self.new()
        with self.helper(prefix='os._exit(8)'): self.rejected(visible=False)

    def test_stalled_startup_expires_before_payload_and_joins_original_child(self):
        self.new(timeout=.6)
        with self.helper(prefix='time.sleep(10)'): self.rejected(visible=False)
        self.gate._issued_child._retired()

    def test_native_cleanup_failure_cannot_publish_buffered_receipt(self):
        self.new(); original = process._SyntheticPayloadPeer.close
        def close(child):
            original(child)
            raise BrokerProcessError('process_cleanup_failed')
        with patch.object(process._SyntheticPayloadPeer, 'close', close):
            self.rejected(visible=True, cleanup=False)

    def test_original_retirement_validation_failure_cannot_publish_receipt(self):
        self.new(); original = process._SyntheticPayloadPeer._retired
        def retired(child):
            original(child)
            raise BrokerProcessError('process_cleanup_failed')
        with patch.object(process._SyntheticPayloadPeer, '_retired', retired):
            self.rejected(visible=True, cleanup=False)

    def test_cancellation_at_final_receipt_validation_withholds_success(self):
        self.new(); self.receipt_fault(lambda evidence: self.gate.cancel())

    def test_receipt_count_mutation_is_not_a_valid_native_fact(self):
        self.new()
        self.receipt_fault(lambda evidence: object.__setattr__(evidence, 'byte_count', len(self.DATA)+1))

    def test_receipt_digest_mutation_is_not_a_valid_native_fact(self):
        self.new()
        self.receipt_fault(lambda evidence: object.__setattr__(evidence, 'digest', 'a'*64))

    def test_receipt_outcome_mutation_cannot_manufacture_permission(self):
        self.new()
        self.receipt_fault(lambda evidence: object.__setattr__(evidence, 'outcome', 'allow_once'))

    def test_receipt_binding_mutation_is_rejected(self):
        self.new()
        self.receipt_fault(lambda evidence: object.__setattr__(evidence, 'canonical_binding', b'{}'))

    def test_receipt_meaning_mutation_is_rejected(self):
        self.new()
        self.receipt_fault(lambda evidence: object.__setattr__(evidence, 'meaning', 'permission'))

    def test_receipt_boolean_count_cannot_match_an_integer_bound(self):
        self.new(b'x')
        self.receipt_fault(lambda evidence: object.__setattr__(evidence, 'byte_count', True))

    def test_receipt_binding_digest_mutation_is_rejected(self):
        self.new()
        self.receipt_fault(lambda evidence: object.__setattr__(evidence, 'binding_digest', 'a'*64))

    def test_oversized_receipt_prefix_fails_without_allocating_large_body(self):
        self.new()
        prefix = 'entry.SyntheticPayloadExchange.receipt = lambda self: (8192+33).to_bytes(4,"big")'
        with self.helper(prefix=prefix): self.rejected(visible=True)

    def test_undersized_receipt_prefix_is_unknown_not_success(self):
        self.new()
        prefix = 'entry.SyntheticPayloadExchange.receipt = lambda self: (31).to_bytes(4,"big")'
        with self.helper(prefix=prefix): self.rejected(visible=True)

    def test_ready_exact_count_substitution_is_rejected_before_payload(self):
        self.new()
        prefix = ('original = entry.SyntheticPayloadExchange._expected\n'
            'def expected(self,phase):\n value=original(self,phase)\n'
            ' if phase==1: value["byte_count"]+=1\n return value\n'
            'entry.SyntheticPayloadExchange._expected=expected')
        with self.helper(prefix=prefix): self.rejected(visible=False)

    def test_native_creation_time_substitution_is_rejected_before_payload(self):
        self.new(); original = SyntheticPayloadExchange.prepare
        def prepare(codec, envelope):
            value = copy.deepcopy(envelope); value['channel']['creation_time'] += 1
            return original(codec, value)
        with patch.object(SyntheticPayloadExchange, 'prepare', prepare): self.rejected(visible=False)

    def test_authenticated_authority_field_cannot_extend_fixed_child_contract(self):
        self.new(); original = SyntheticPayloadExchange.prepare
        def prepare(codec, envelope):
            original(codec, envelope)
            value = copy.deepcopy(envelope); value['permission'] = 'allow_once'
            return codec._frame('request', value)
        with patch.object(SyntheticPayloadExchange, 'prepare', prepare): self.rejected(visible=False)

    def test_authenticated_file_selector_cannot_extend_fixed_child_contract(self):
        self.new(); original = SyntheticPayloadExchange.prepare
        def prepare(codec, envelope):
            original(codec, envelope)
            value = copy.deepcopy(envelope); value['path'] = 'C:\\personal'
            return codec._frame('request', value)
        with patch.object(SyntheticPayloadExchange, 'prepare', prepare): self.rejected(visible=False)

    def test_generated_id_collision_is_rejected_before_payload(self):
        self.new()
        with patch.object(native.secrets, 'token_hex', return_value='a'*64):
            self.rejected(visible=False)

    def test_generated_session_id_collision_is_rejected_before_payload(self):
        self.new()
        with patch.object(native.secrets, 'token_bytes', return_value=b'a'*32), \
                patch.object(native.secrets, 'token_hex', side_effect=['61'*32, 'b'*64]):
            self.rejected(visible=False)

    def test_malformed_generated_bootstrap_key_prevents_native_launch(self):
        self.new()
        with patch.object(native.secrets, 'token_bytes', return_value=b'x'), \
                patch.object(native, '_SyntheticPayloadPeer') as launch:
            self.rejected(visible=False); launch.assert_not_called()

    def test_single_original_owner_alias_mutation_rejects_and_wipes_original_only(self):
        for name in ('_origin', '_issued_origin', '_recovery_origin'):
            with self.subTest(name=name):
                self.new(); original = self.gate._origin; foreign = bytearray(b'foreign')
                codec_ready = SyntheticPayloadExchange.accept_ready; reached = []
                def ready(codec, frame):
                    result = codec_ready(codec, frame); reached.append(True)
                    setattr(self.gate, name, foreign); return result
                try:
                    with patch.object(SyntheticPayloadExchange, 'accept_ready', ready), \
                            self.assertRaises(native.SyntheticPayloadTransportError):
                        self.gate.run()
                finally:
                    setattr(self.gate, name, original)
                self.assertEqual(reached, [True])
                self.assertEqual(original.buffer, bytearray())
                self.assertEqual(foreign, bytearray(b'foreign'))
                self.assertEqual(self.diagnostic()['state'], 'failed_before_payload')

    def test_single_state_alias_mutation_cannot_restore_unused_attempt(self):
        for name in ('_history', '_issued_history', '_recovery_history'):
            with self.subTest(name=name):
                self.new()
                self.ready_fault(lambda: setattr(self.gate, name, None))
                with self.assertRaises(native.SyntheticPayloadTransportError): self.gate.run()

    def test_foreign_child_field_never_selects_a_foreign_cleanup_target(self):
        class Foreign:
            def close(self): raise AssertionError('foreign cleanup invoked')
            def _retired(self): raise AssertionError('foreign retirement invoked')
        for name in ('_child', '_issued_child'):
            with self.subTest(name=name):
                self.new(); original_ready = SyntheticPayloadExchange.accept_ready
                original_child = []
                def ready(codec, frame):
                    value = original_ready(codec, frame)
                    original_child.append(self.gate._issued_child)
                    setattr(self.gate, name, Foreign()); return value
                with patch.object(SyntheticPayloadExchange, 'accept_ready', ready):
                    self.rejected(visible=False)
                self.assertEqual(len(original_child), 1)
                original_child[0]._retired()

    def test_native_observation_substitution_is_rejected_before_payload(self):
        self.new()
        self.ready_fault(lambda: setattr(self.gate, '_native_observation', None))

    def test_exported_original_buffer_view_is_zeroed_and_cleanup_uncertainty_withholds_fact(self):
        self.new(); view = memoryview(self.gate._origin.buffer)
        try:
            self.rejected(visible=True, cleanup=False)
            self.assertEqual(bytes(view), b'\0'*len(self.DATA))
        finally: view.release()

    def test_archived_result_mutation_cannot_manufacture_permission_or_new_attempt(self):
        value = self.success(); object.__setattr__(value, 'outcome', 'allow_once')
        with self.assertRaises(native.SyntheticPayloadTransportError): self.gate.inspect()
        with self.assertRaises(native.SyntheticPayloadTransportError): self.gate.cancel()
        with self.assertRaises(native.SyntheticPayloadTransportError): self.gate.run()

    def test_result_binding_inspection_is_detached(self):
        value = self.success(); inspected = value.inspect()
        inspected['channel']['pid'] = 1
        inspected['byte_count'] = 0
        self.assertNotEqual(value.inspect()['channel']['pid'], 1)
        self.assertEqual(value.inspect()['byte_count'], len(self.DATA))

    def test_launch_cleanup_failure_is_explicitly_unconfirmed(self):
        self.new()
        with patch.object(process._SyntheticPayloadPeer, '__init__',
                side_effect=BrokerProcessError('process_cleanup_failed')):
            self.rejected(visible=False, cleanup=False)

    def test_noop_original_buffer_wipe_withholds_receipt_and_marks_cleanup_uncertain(self):
        self.new()
        with patch.object(native.SyntheticPayloadTransport, '_wipe', return_value=None):
            self.rejected(visible=True, cleanup=False)
        self.assertEqual(bytes(self.gate._origin.buffer), self.DATA)
        native.SyntheticPayloadTransport._wipe(self.gate._origin)

    def candidate_fault(self, stage):
        self.new(); candidates = []
        original_init = native.NativeSyntheticPayloadEvidence.__init__
        def initialize(value, *args, **options):
            original_init(value, *args, **options); candidates.append(value)
        def mutate():
            self.assertEqual(len(candidates), 1)
            object.__setattr__(candidates[0], 'byte_count', len(self.DATA)+1)
        if stage == 'native':
            target, field = process._SyntheticPayloadPeer, 'close'
            original = target.close
            def operation(child):
                value = original(child); mutate(); return value
        elif stage == 'codec':
            target, field = SyntheticPayloadExchange, 'close'
            original = target.close
            def operation(codec):
                value = original(codec); mutate(); return value
        else:
            target, field = native.SyntheticPayloadTransport, '_wipe'
            original = target._wipe
            def operation(owner):
                value = original(owner); mutate(); return value
        with patch.object(native.NativeSyntheticPayloadEvidence, '__init__', initialize), \
                patch.object(target, field, staticmethod(operation) if stage == 'wipe' else operation):
            self.rejected(visible=True)
        self.assertEqual(len(candidates), 1)

    def test_candidate_mutation_during_original_native_close_is_rejected(self):
        self.candidate_fault('native')

    def test_candidate_mutation_during_original_codec_close_is_rejected(self):
        self.candidate_fault('codec')

    def test_candidate_mutation_during_original_buffer_wipe_is_rejected(self):
        self.candidate_fault('wipe')

    def test_foreign_codec_lock_is_never_acquired_for_progress_or_disposal(self):
        calls = []
        class ForeignLock:
            def acquire(self, *args, **options): calls.append('acquire'); raise AssertionError('foreign codec acquire')
            def __enter__(self): calls.append('enter'); raise AssertionError('foreign codec context')
            def __exit__(self, *args): calls.append('exit'); raise AssertionError('foreign codec exit')
        self.new(); original = SyntheticPayloadExchange.accept_ready; reached = []
        def ready(codec, frame):
            value = original(codec, frame); reached.append(True)
            codec._lock = ForeignLock(); return value
        with patch.object(SyntheticPayloadExchange, 'accept_ready', ready):
            self.rejected(visible=False)
        self.assertEqual(reached, [True])
        self.assertEqual(calls, [])

    def test_foreign_native_lock_is_never_acquired_and_original_child_is_joined(self):
        calls = []
        class ForeignLock:
            def acquire(self, *args, **options): calls.append('acquire'); raise AssertionError('foreign native acquire')
            def __enter__(self): calls.append('enter'); raise AssertionError('foreign native context')
            def __exit__(self, *args): calls.append('exit'); raise AssertionError('foreign native exit')
        self.new()
        self.ready_fault(lambda: setattr(self.gate._issued_child, '_ownership_lock', ForeignLock()))
        self.gate._issued_child._retired()
        self.assertEqual(calls, [])

    def test_busy_original_native_lock_does_not_block_transport_cleanup(self):
        self.new(); acquired, release = threading.Event(), threading.Event()
        original_ready = SyntheticPayloadExchange.accept_ready
        holder, started = [], []
        child = []
        def ready(codec, frame):
            value = original_ready(codec, frame)
            child.append(self.gate._issued_child)
            def hold():
                with child[0]._ownership_lock:
                    acquired.set(); release.wait(3)
            thread = threading.Thread(target=hold); holder.append(thread); thread.start()
            self.assertTrue(acquired.wait(2)); started.append(time.monotonic())
            return value
        try:
            with patch.object(SyntheticPayloadExchange, 'accept_ready', ready):
                self.rejected(visible=False, cleanup=False)
            self.assertEqual(len(started), 1)
            self.assertLess(time.monotonic()-started[0], .3)
        finally:
            release.set()
            for thread in holder: thread.join(3)
            for original_child in child: original_child.close(); original_child._retired()
        self.assertFalse(any(thread.is_alive() for thread in holder))

    def test_expiry_during_terminal_native_close_withholds_prepared_fact(self):
        self.new(); original_close = process._SyntheticPayloadPeer.close
        original_clock, clock = native.monotonic, [None]
        def monotonic(): return original_clock() if clock[0] is None else clock[0]
        def close(child):
            value = original_close(child)
            clock[0] = self.gate._origin.deadline + 1
            return value
        with patch.object(native, 'monotonic', monotonic), \
                patch.object(process._SyntheticPayloadPeer, 'close', close):
            self.rejected(visible=True)

    def test_channel_field_mutation_during_terminal_native_close_withholds_fact(self):
        self.new(); original_close = process._SyntheticPayloadPeer.close
        def close(child):
            value = original_close(child)
            self.gate._native_observation = None
            return value
        with patch.object(process._SyntheticPayloadPeer, 'close', close): self.rejected(visible=True)

    def test_duplicate_running_admission_cancels_sole_worker_without_retry(self):
        self.new(); reached, release = threading.Event(), threading.Event()
        original = SyntheticPayloadExchange.accept_ready
        errors = []
        def ready(codec, frame):
            value = original(codec, frame); reached.set()
            if not release.wait(2): raise AssertionError('worker release not delivered')
            return value
        def run():
            try: self.gate.run()
            except native.SyntheticPayloadTransportError as error: errors.append(error)
        with patch.object(SyntheticPayloadExchange, 'accept_ready', ready):
            worker = threading.Thread(target=run); worker.start()
            try:
                self.assertTrue(reached.wait(2))
                with self.assertRaises(native.SyntheticPayloadTransportError): self.gate.run()
            finally:
                release.set(); worker.join(3)
            self.assertFalse(worker.is_alive())
        self.assertEqual(len(errors), 1)
        self.assertEqual(self.diagnostic()['state'], 'cancelled_before_payload')
        self.gate._issued_child._retired()

    def final_retired_fault(self, operation):
        self.new(); original = process._SyntheticPayloadPeer._retired; reached = []
        def retired(child):
            original(child); reached.append(True)
            if len(reached) == 2: operation(child)
        with patch.object(process._SyntheticPayloadPeer, '_retired', retired):
            self.rejected(visible=True)
        self.assertEqual(len(reached), 2, 'fault occurs after final native callback, before fact sealing')

    def test_cancellation_from_final_native_retired_callback_cannot_be_overwritten_by_success(self):
        self.final_retired_fault(lambda child: self.gate.cancel())

    def test_boolean_retired_exit_snapshot_from_final_callback_is_rejected(self):
        self.final_retired_fault(lambda child: setattr(child, '_retired_snapshot', (False, True)))

    def test_boolean_native_creation_time_from_final_callback_is_rejected(self):
        self.final_retired_fault(lambda child: object.__setattr__(child._issued_observation, 'creation_time', True))

    def test_boolean_native_pid_from_final_callback_is_rejected(self):
        self.final_retired_fault(lambda child: object.__setattr__(child._issued_observation, 'pid', True))

    def test_changed_original_owned_tuple_from_final_callback_is_rejected(self):
        self.final_retired_fault(lambda child: setattr(child, '_owned', tuple(list(child._owned))))

    def test_prestart_cancel_noop_wipe_is_spent_and_cleanup_unconfirmed_without_launch(self):
        self.new()
        with patch.object(native.SyntheticPayloadTransport, '_wipe', return_value=None):
            self.rejected(self.gate.cancel, visible=False, cleanup=False)
        self.assertEqual(self.diagnostic()['state'], 'cancelled_before_payload')
        with patch.object(native, '_SyntheticPayloadPeer') as launch:
            self.rejected(visible=False, cleanup=False); launch.assert_not_called()
        native.SyntheticPayloadTransport._wipe(self.gate._origin)

    def test_prestart_owner_alias_damage_and_noop_wipe_cannot_reopen_attempt(self):
        self.new(); original = self.gate._origin; self.gate._origin = None
        try:
            with patch.object(native.SyntheticPayloadTransport, '_wipe', return_value=None), \
                    patch.object(native, '_SyntheticPayloadPeer') as launch:
                with self.assertRaises(native.SyntheticPayloadTransportError): self.gate.run()
                launch.assert_not_called()
        finally: self.gate._origin = original
        value = self.diagnostic()
        self.assertEqual(value['state'], 'failed_before_payload')
        self.assertIs(value['cleanup_confirmed'], False)
        with patch.object(native, '_SyntheticPayloadPeer') as launch:
            self.rejected(visible=False, cleanup=False); launch.assert_not_called()
        native.SyntheticPayloadTransport._wipe(original)

    def test_cancel_only_signals_and_worker_remains_native_cleanup_owner(self):
        self.new(); reached, release = threading.Event(), threading.Event()
        original = SyntheticPayloadExchange.accept_ready
        errors, close_threads = [], []
        original_close = process._SyntheticPayloadPeer.close
        def ready(codec, frame):
            value = original(codec, frame); reached.set()
            if not release.wait(2): raise AssertionError('test worker release not delivered')
            return value
        def close(child):
            close_threads.append(threading.get_ident()); return original_close(child)
        def run():
            try: self.gate.run()
            except native.SyntheticPayloadTransportError as error: errors.append(error)
        with patch.object(SyntheticPayloadExchange, 'accept_ready', ready), \
                patch.object(process._SyntheticPayloadPeer, 'close', close):
            worker = threading.Thread(target=run); worker.start()
            try:
                self.assertTrue(reached.wait(2))
                caller = threading.get_ident(); started = time.monotonic()
                self.gate.cancel()
                self.assertLess(time.monotonic()-started, .2)
                self.assertEqual(close_threads, [])
            finally:
                release.set(); worker.join(3)
            self.assertFalse(worker.is_alive())
        self.assertEqual(len(errors), 1)
        self.assertTrue(close_threads)
        self.assertNotIn(caller, close_threads)
        self.assertEqual(self.diagnostic()['state'], 'cancelled_before_payload')


if __name__ == '__main__': unittest.main()
